version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    networks:
      - internal
    environment:
      - DB_USER=frontend_user
      - DB_PASS=securepass123
      - GIT_SSH_COMMAND=ssh -i /home/opamuser/.ssh/id_ed25519 -o IdentitiesOnly=yes
      # - GIT_SSH_COMMAND=ssh -i /root/.ssh/id_ed25519 -o IdentitiesOnly=yes git clone blabla
    volumes:
      - ./frontend:/app
      - /home/matiasdanmansilla/.ssh:/home/opamuser/.ssh:ro
    ports:
      - "8080:8080"  # o el puerto que uses
    # TEMP esto es para mantener la sesion abierta
    stdin_open: true
    tty: true

  trader:
    build: ./trader
    container_name: trader
    networks:
      - internal
    environment:
      - DB_USER=trader_user
      - DB_PASS=securepass456
    volumes:
      - ./trader:/app

networks:
  internal:

